<?php
    declare(strict_types=1);
    /** @var ShareToKarakeepExtension $this */
?>
<form action="<?= _url('extension', 'configure', 'e', urlencode($this->getName())); ?>" method="post" data-auto-leave-validation="1">
    <input type="hidden" name="_csrf" value="<?= FreshRSS_Auth::csrfToken() ?>" />
    <div class="form-group">
        <label class="group-name" for="karakeep_url"><?= _t('share_to_karakeep.config.karakeep_url') ?></label>
        <div class="group-controls">
            <input type="url" name="karakeep_url" id="karakeep_url" value="<?= FreshRSS_Context::$user_conf->karakeep_url ?? '' ?>" />
        </div>
    </div>
    <div class="form-group">
        <label class="group-name" for="karakeep_token"><?= _t('share_to_karakeep.config.karakeep_token') ?></label>
        <div class="group-controls">
            <input type="password" name="karakeep_token" id="karakeep_token" value="<?= FreshRSS_Context::$user_conf->karakeep_token ?? '' ?>" />
        </div>
    </div>

    <div class="form-group form-actions">
        <div class="group-controls">
            <button type="submit" class="btn btn-important"><?= _t('gen.action.submit') ?></button>
            <button type="reset" class="btn"><?= _t('gen.action.cancel') ?></button>
        </div>
    </div>
</form>
